### ISSUE TITLE
Revoke express-graphql dependency since is deprecated module

### ISSUE THREAD

**Issue by ThePlenkov** [cap-js/cds-adapter-graphql#22]
Hi! 

As it's declared here https://github.com/graphql/express-graphql#this-library-is-deprecated express-graphql is not recommended for use anymore. It's using outdated approach.

I'd recommend to switch to https://github.com/graphql/graphql-http

Here is the example how it should be used with express.
https://github.com/graphql/graphql-http#with-express

Also may be it makes sense to think of even starting a separate graphql server, for example by use of Yoga:
https://github.com/graphql/graphql-http#servers

What do you think? 

Thanks!

**Comment by ThePlenkov** [comment]
Here is the example how to use Yoga with express:
https://the-guild.dev/graphql/yoga-server/docs/integrations/integration-with-express#example

**Comment by schwma** [comment]
Hi @ThePlenkov,

thanks for the info! We are aware that `express-graphql` has been deprecated and are in the process of finding a suitable replacement. The decision has not yet been made and we are including the options you mentioned above in our evaluation.

Best regards,
Marcel

**Comment by schwma** [comment]
Hi @ThePlenkov,

We have replaced `express-graphql` with `graphql-http` as the underlying GraphQL HTTP server. Since `graphql-http` does not include GraphiQL, we have included this ourselves in HTML that we serve. `express-graphql` included GraphiQL 1 and we have now upgraded to GraphiQL 2.

Best regards,
Marcel

**Comment by ThePlenkov** [comment]
@schwma I have tried 0.3.0 and now I have this message:
`Error: ENOENT: no such file or directory, stat '/workspace/node_modules/@cap-js/graphql/app/graphiql.html'`

**Comment by ThePlenkov** [comment]
registered here #49

**Comment by ThePlenkov** [comment]
That's amazing - now we can finally use headers. Thansk!
