### ISSUE TITLE
Support native cap authentication

### ISSUE THREAD

**Issue by ThePlenkov** [cap-js/cds-adapter-graphql#23]
I'd like to report also one more issue ew face currently

We've created a custom authorization layer by use of the following config
`"auth": {
      "impl": "srv/auth.js"
    }
` where we implement is function to check user roles https://cap.cloud.sap/docs/node.js/authentication#user-is 
However in case of graphql requests this code is simply not called.
I think i'd be nice to support auth here too.

Thanks!

**Comment by schwma** [comment]
Could you please let me know which version of the GraphQL adapter and `@sap/cds` this occurred with?

**Comment by ThePlenkov** [comment]
let me please upgrade versions to the most recent ones and try one more time  - will reply shortly the result

**Comment by ThePlenkov** [comment]
i checked - it works as expected now.

**Comment by schwma** [comment]
Great, thanks for the update!
