### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '.../@cap-js/graphql/app/graphiql.html'

### ISSUE THREAD

**Issue by ThePlenkov** [cap-js/cds-adapter-graphql#49]
Hi! After upgrading to 0.3.0 I have now this error message:
`Error: ENOENT: no such file or directory, stat '/workspace/node_modules/@cap-js/graphql/app/graphiql.html'`

It looks like app folder hasn't been published:
https://www.npmjs.com/package/@cap-js/graphql?activeTab=explore

**Comment by schwma** [comment]
Hi @ThePlenkov, you're right, the problem is that unfortunately the `app/` folder wasn't included when publishing the package to `npm` (needs to be included in the `package.json`). Thank you for making us aware of the issue!

**Comment by schwma** [comment]
Hi @ThePlenkov, we just released a new [version](https://github.com/cap-js/cds-adapter-graphql/releases/tag/v0.3.1) that includes this fix
